// This file was automatically generated on 2015-01-08.
using System;
using System.Collections.Generic;

namespace X509CertificateKeyPinning
{
    public class Google
    {
        public static readonly KeyValuePair<string, string>[] RootPublicKeyHashes = new KeyValuePair<string, string>[]
        {
            new KeyValuePair<string, string>("CN=GTE CyberTrust Global Root, OU=\"GTE CyberTrust Solutions, Inc.\", O=GTE Corporation, C=US", "9YIfQ1jnd0YpKAWOUPPGmeYXyLrx5oqUXFqkv38zfZU="),
            new KeyValuePair<string, string>("E=server-certs@thawte.com, CN=Thawte Server CA, OU=Certification Services Division, O=Thawte Consulting cc, L=Cape Town, S=Western Cape, C=ZA", "A1w5nCZqxYbgxJF8XseFCJmAoWmbRCPd6TrDzaAvT1M="),
            new KeyValuePair<string, string>("E=premium-server@thawte.com, CN=Thawte Premium Server CA, OU=Certification Services Division, O=Thawte Consulting cc, L=Cape Town, S=Western Cape, C=ZA", "Lhg7aGKKRVUS4NnDH/KTPOINz58fm38gkd4eYFL07HE="),
            new KeyValuePair<string, string>("OU=Equifax Secure Certificate Authority, O=Equifax, C=US", "eI2rxtI5Da2HZ9jbXUoe2s2sf0FU4m3/Spczsy12Pm4="),
            new KeyValuePair<string, string>("OU=Class 3 Public Primary Certification Authority, O=\"VeriSign, Inc.\", C=US", "1MZ61Q4ZO511oiHSYDMJFxV0rngsZtumRKaK/3XAf1A="),
            new KeyValuePair<string, string>("OU=VeriSign Trust Network, OU=\"(c) 1998 VeriSign, Inc. - For authorized use only\", OU=Class 3 Public Primary Certification Authority - G2, O=\"VeriSign, Inc.\", C=US", "qHLt8EqOb/DK+k+rxpM2RS7AuoKIt08hm5kDXszXpM8="),
            new KeyValuePair<string, string>("CN=GlobalSign Root CA, OU=Root CA, O=GlobalSign nv-sa, C=BE", "Pd4y/8Rwm7Gj/3bTVEH0rn/gXuKK5dYXp1vTbu5r9co="),
            new KeyValuePair<string, string>("CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R2", "JYglO5pBUiQUrcOrovC4F787qgx6DBlkaU9/Xv/EuWA="),
            new KeyValuePair<string, string>("E=info@valicert.com, CN=http://www.valicert.com/, OU=ValiCert Class 1 Policy Validation Authority, O=\"ValiCert, Inc.\", L=ValiCert Validation Network", "Dhqh2OLIk9kyOpdaP4xCasXXfKrCwtQ5pO3HhRBoLt4="),
            new KeyValuePair<string, string>("E=info@valicert.com, CN=http://www.valicert.com/, OU=ValiCert Class 2 Policy Validation Authority, O=\"ValiCert, Inc.\", L=ValiCert Validation Network", "lQYyyFmQJQQmsmGkh59BDryXoXgnKTP17m3HDT/zv3o="),
            new KeyValuePair<string, string>("E=info@valicert.com, CN=http://www.valicert.com/, OU=ValiCert Class 3 Policy Validation Authority, O=\"ValiCert, Inc.\", L=ValiCert Validation Network", "DNsVqQIZq0hKMSyJev6fpYDtdKbNNWtfUX+ifcWE4qw="),
            new KeyValuePair<string, string>("CN=VeriSign Class 3 Public Primary Certification Authority - G3, OU=\"(c) 1999 VeriSign, Inc. - For authorized use only\", OU=VeriSign Trust Network, O=\"VeriSign, Inc.\", C=US", "noa3ADvmDqvo4XJ/2xHgWdheHAHe/jzzP0RjedVUOgY="),
            new KeyValuePair<string, string>("CN=VeriSign Class 4 Public Primary Certification Authority - G3, OU=\"(c) 1999 VeriSign, Inc. - For authorized use only\", OU=VeriSign Trust Network, O=\"VeriSign, Inc.\", C=US", "cxEOLr6Qx4UjXQswHXUEuAHOZAEUjOP9y1fTCHI7cco="),
            new KeyValuePair<string, string>("CN=Entrust.net Secure Server Certification Authority, OU=(c) 1999 Entrust.net Limited, OU=www.entrust.net/CPS incorp. by ref. (limits liab.), O=Entrust.net, C=US", "NBfFHHhQM+nYJqr0cpHp4yaJJ6o2RvXs2N6NdH2JYe0="),
            new KeyValuePair<string, string>("CN=Entrust.net Certification Authority (2048), OU=(c) 1999 Entrust.net Limited, OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), O=Entrust.net", "BjSMqQ1/4PkMdqud6CKr9XuatEIqtPg+m4aDrFHfN5U="),
            new KeyValuePair<string, string>("CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE", "pn/iqa+WfLW//cnr2o8ateq8olTxA5ZSd/1Loz4noYc="),
            new KeyValuePair<string, string>("CN=Equifax Secure Global eBusiness CA-1, O=Equifax Secure Inc., C=US", "6ZF+CTa875+g9v92lu1ihpShfuiC0JuXrBYTE4+Ykzs="),
            new KeyValuePair<string, string>("CN=Equifax Secure eBusiness CA-1, O=Equifax Secure Inc., C=US", "m/dnaRLnxK8cGKVlwJ8J+Mw/jxmH8t/Mj/fi0knYHWE="),
            new KeyValuePair<string, string>("OU=Equifax Secure eBusiness CA-2, O=Equifax Secure, C=US", "zp8jzgssx36JFmwBMQ9+gO80pvTutZyVIq0jvBc9sFY="),
            new KeyValuePair<string, string>("CN=AddTrust Class 1 CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE", "TlzaE2uSG1gojqP1jPEsqzCgrohfEoj6uQ2EeMUy+Qg="),
            new KeyValuePair<string, string>("CN=AddTrust External CA Root, OU=AddTrust External TTP Network, O=AddTrust AB, C=SE", "uthKDtpuYHgn+wRsokVptSysyqBzmr4RP86mOC703bg="),
            new KeyValuePair<string, string>("CN=AddTrust Public CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE", "X/sIi9IWd4e91o3T2pJPuI99Cdm4mqi3qUN3yAAVo9c="),
            new KeyValuePair<string, string>("CN=AddTrust Qualified CA Root, OU=AddTrust TTP Network, O=AddTrust AB, C=SE", "IUXquD+WRiLZME813hyZEr6+P/MidpblXDrYhvbBNx8="),
            new KeyValuePair<string, string>("CN=Entrust Root Certification Authority, OU=\"(c) 2006 Entrust, Inc.\", OU=www.entrust.net/CPS is incorporated by reference, O=\"Entrust, Inc.\", C=US", "FwinA34U6oL8reEjqRzN5CBT/shf3gezL9CpPvq57VI="),
            new KeyValuePair<string, string>("CN=GeoTrust Global CA, O=GeoTrust Inc., C=US", "RbpC/rJ2mpVj+lHMJ90Ulu/Q5MXRlomAMxeMyHWPUMo="),
            new KeyValuePair<string, string>("CN=GeoTrust Global CA 2, O=GeoTrust Inc., C=US", "GHGD1FFK7Sj6FcxuJjMdxNKQY+KKw9vfTGk2x8YPDJg="),
            new KeyValuePair<string, string>("CN=GeoTrust Universal CA, O=GeoTrust Inc., C=US", "hQf68p9pbY3tpMzZ70kG+DjTZjeuuTq/IuyZCzMid+s="),
            new KeyValuePair<string, string>("CN=GeoTrust Universal CA 2, O=GeoTrust Inc., C=US", "NyqFsUrdoDrfhOtDaK6WoXKieC9JKTpXPvADWrGx+CY="),
            new KeyValuePair<string, string>("CN=America Online Root Certification Authority 1, O=America Online Inc., C=US", "WclFWGKuRptpm+HADV9QmF0NiYOV1Q/qKLgcYvcaeNk="),
            new KeyValuePair<string, string>("CN=America Online Root Certification Authority 2, O=America Online Inc., C=US", "MzDtD+rrhjJGP9CQZN2m96fi6aM3BNRiF0TLP6L8riE="),
            new KeyValuePair<string, string>("CN=AAA Certificate Services, O=Comodo CA Limited, L=Salford, S=Greater Manchester, C=GB", "yjQSNCyy/pFK4YKzKlxJS7mC5ke1acUncMSEUV/MXuI="),
            new KeyValuePair<string, string>("CN=Secure Certificate Services, O=Comodo CA Limited, L=Salford, S=Greater Manchester, C=GB", "Anw0Pbe8FeXP19H4djx948y3GVYAQlQmsM3V5uw9S3k="),
            new KeyValuePair<string, string>("CN=Trusted Certificate Services, O=Comodo CA Limited, L=Salford, S=Greater Manchester, C=GB", "+l220o/FTYhaRARqQbAxOhFNBUzQkyWnpoCjMmt3xDE="),
            new KeyValuePair<string, string>("CN=UTN - DATACorp SGC, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US", "3oNNs0lMJlbvsWFIUSAWpEm0NnHkjmbcS1mgVFeTX38="),
            new KeyValuePair<string, string>("CN=UTN-USERFirst-Hardware, OU=http://www.usertrust.com, O=The USERTRUST Network, L=Salt Lake City, S=UT, C=US", "eYV8pY4K6zlJdEVC+qrtvT7+siPVdRwH4jQrPX4rxUo="),
            new KeyValuePair<string, string>("CN=XRamp Global Certification Authority, O=XRamp Security Services Inc, OU=www.xrampsecurity.com, C=US", "6NS4ss0CfVBxjjtGCeNEZL0Avt49KePotJt88He2O0o="),
            new KeyValuePair<string, string>("OU=Go Daddy Class 2 Certification Authority, O=\"The Go Daddy Group, Inc.\", C=US", "t6ww3QY+5gNa20lA42m2TjxIGaMhqkkfuKDNaislnqc="),
            new KeyValuePair<string, string>("OU=Starfield Class 2 Certification Authority, O=\"Starfield Technologies, Inc.\", C=US", "tE4juFrcCIiI+8mjvrGgUbEXBnSUUUl/xpyKUg7gr+o="),
            new KeyValuePair<string, string>("CN=StartCom Certification Authority, OU=Secure Digital Certificate Signing, O=StartCom Ltd., C=IL", "xzmuHfzI3Bl+VmJ/0MzlH4prJl5hjfK3+tv7lq7h7YI="),
            new KeyValuePair<string, string>("CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US", "pEPaA2VOo/80IF3/ZaRGiN8JU6PvsmW8PdYITfDfR4w="),
            new KeyValuePair<string, string>("CN=DigiCert Global Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US", "lKdU1EbQubxyDDm2q3N8KclZ2C94Num3xXjG0pk+3eI="),
            new KeyValuePair<string, string>("CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US", "5dR/AvJ0l4HBhKs8D1SecWuyMUJKch/sO9+hN0eeHhU="),
            new KeyValuePair<string, string>("CN=GeoTrust Primary Certification Authority, O=GeoTrust Inc., C=US", "kSS3vyKqVw9xVzSrOTvxPLTK9RR4T8jdABf1rcbC6tU="),
            new KeyValuePair<string, string>("CN=thawte Primary Root CA, OU=\"(c) 2006 thawte, Inc. - For authorized use only\", OU=Certification Services Division, O=\"thawte, Inc.\", C=US", "upfmdva3WJgIiiXfWm+SL5bwQNGeIJy3GLhyuww0RK4="),
            new KeyValuePair<string, string>("CN=VeriSign Class 3 Public Primary Certification Authority - G5, OU=\"(c) 2006 VeriSign, Inc. - For authorized use only\", OU=VeriSign Trust Network, O=\"VeriSign, Inc.\", C=US", "cI+UZW6tdxZr6TM4Wze31Y9/ELKMEmxkp4Ybxmu2Z8Q="),
            new KeyValuePair<string, string>("CN=COMODO Certification Authority, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB", "wgz/BHI2EnYhILELU3ugEA3Q8YJjWtuiRhaKmO2azjQ="),
            new KeyValuePair<string, string>("CN=Network Solutions Certificate Authority, O=Network Solutions L.L.C., C=US", "U4gvtmcA9c/Ofseemidyw7qbwsNvEcxhmxARtimPLo0="),
            new KeyValuePair<string, string>("CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB", "JrAAOGX2d/RaVyKjgDs6IJOYH9ajknEJ2tTF9e10Kjg="),
            new KeyValuePair<string, string>("CN=TC TrustCenter Class 2 CA II, OU=TC TrustCenter Class 2 CA, O=TC TrustCenter GmbH, C=DE", "beUklEwYL2OpR+xTd8r1cx7tkbt/OTl8F3y3Y6q7+Ko="),
            new KeyValuePair<string, string>("CN=TC TrustCenter Class 3 CA II, OU=TC TrustCenter Class 3 CA, O=TC TrustCenter GmbH, C=DE", "IhqcuUZ9XM36zqvdT2gqU36GF/4eL42etpYOmsn7V+k="),
            new KeyValuePair<string, string>("CN=TC TrustCenter Universal CA I, OU=TC TrustCenter Universal CA, O=TC TrustCenter GmbH, C=DE", "oXinideGwFOKUYHuvXNHqApMZi9gYB91MfG85HUOJH8="),
            new KeyValuePair<string, string>("CN=Cybertrust Global Root, O=\"Cybertrust, Inc\"", "ZRsK32dOEQYwKlGpr6IU4hOOiHc+GvP2YgKNq2Nyjs8="),
            new KeyValuePair<string, string>("CN=GeoTrust Primary Certification Authority - G3, OU=(c) 2008 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US", "wggnVRmeWLlgSif9EQAHQoowIPFrimBB6KX+VmR27+g="),
            new KeyValuePair<string, string>("CN=thawte Primary Root CA - G2, OU=\"(c) 2007 thawte, Inc. - For authorized use only\", O=\"thawte, Inc.\", C=US", "ot6nJpHB8SDQM2Vg0suLYzHpT9ZXZQrIXYi/jlDkzDI="),
            new KeyValuePair<string, string>("CN=thawte Primary Root CA - G3, OU=\"(c) 2008 thawte, Inc. - For authorized use only\", OU=Certification Services Division, O=\"thawte, Inc.\", C=US", "DWUoR3AjwW+xHubDWlJQTE5EG1kZSR9fNZ7VDrMFm4o="),
            new KeyValuePair<string, string>("CN=GeoTrust Primary Certification Authority - G2, OU=(c) 2007 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US", "a7lfu+RaUlS8TAZ+84lKVxHd7x/+uyVyvWcvcgq1eaU="),
            new KeyValuePair<string, string>("CN=VeriSign Universal Root Certification Authority, OU=\"(c) 2008 VeriSign, Inc. - For authorized use only\", OU=VeriSign Trust Network, O=\"VeriSign, Inc.\", C=US", "1jGyRgJ8qI6bA0JPIwyfNTNStJpfmnMVVm3CrGjQWBY="),
            new KeyValuePair<string, string>("CN=VeriSign Class 3 Public Primary Certification Authority - G4, OU=\"(c) 2007 VeriSign, Inc. - For authorized use only\", OU=VeriSign Trust Network, O=\"VeriSign, Inc.\", C=US", "irC9QNve1pOJOpaXnMPWwj7U3oEtMGEQ3zn6+lFIwxA="),
            new KeyValuePair<string, string>("OU=Class 3 Public Primary Certification Authority, O=\"VeriSign, Inc.\", C=US", "1MZ61Q4ZO511oiHSYDMJFxV0rngsZtumRKaK/3XAf1A="),
            new KeyValuePair<string, string>("CN=GlobalSign, O=GlobalSign, OU=GlobalSign Root CA - R3", "OaR1hwvytIxSA6COpSJ5vOcau40+N+BriQeiZ+zX2mo="),
            new KeyValuePair<string, string>("CN=TC TrustCenter Universal CA III, OU=TC TrustCenter Universal CA, O=TC TrustCenter GmbH, C=DE", "Be+mMw8ktoR1wfVqxiAicJ0nU7Hs0613db5fAGh6f48="),
            new KeyValuePair<string, string>("CN=Go Daddy Root Certificate Authority - G2, O=\"GoDaddy.com, Inc.\", L=Scottsdale, S=Arizona, C=US", "mN+4boFKKEM8vn/gTnNvY5ejLfLJsKCL1QoyUYfgx3A="),
            new KeyValuePair<string, string>("CN=Starfield Root Certificate Authority - G2, O=\"Starfield Technologies, Inc.\", L=Scottsdale, S=Arizona, C=US", "UAvhT0JXPy1OcxbkXY/Oc9057XvOf1Gr2QNeL6l2QYE="),
            new KeyValuePair<string, string>("CN=Starfield Services Root Certificate Authority - G2, O=\"Starfield Technologies, Inc.\", L=Scottsdale, S=Arizona, C=US", "IluA1v9TE2XcrcYkqkmDGqLd+EHxHKR9D8TXUk4Et0A="),
            new KeyValuePair<string, string>("CN=AffirmTrust Commercial, O=AffirmTrust, C=US", "dp+KODo2lyfiAG4TYjvIiXi7SVQkmOQIWuM5k+v/a74="),
            new KeyValuePair<string, string>("CN=AffirmTrust Networking, O=AffirmTrust, C=US", "km6ee3l/dLPJsT6Ber6bSxl5OySDqPgBFCVwwfnJ8h4="),
            new KeyValuePair<string, string>("CN=AffirmTrust Premium, O=AffirmTrust, C=US", "u65rZDriboHgBfnxQrOZucmSqO4UKqfNoSj1WAqp1Ys="),
            new KeyValuePair<string, string>("CN=AffirmTrust Premium ECC, O=AffirmTrust, C=US", "784iBVlLAo/W0aAlBd+ePeDMk3m9IQ2Y667hFU+X0p8="),
            new KeyValuePair<string, string>("CN=StartCom Certification Authority, OU=Secure Digital Certificate Signing, O=StartCom Ltd., C=IL", "xzmuHfzI3Bl+VmJ/0MzlH4prJl5hjfK3+tv7lq7h7YI="),
            new KeyValuePair<string, string>("CN=StartCom Certification Authority G2, O=StartCom Ltd., C=IL", "b0TRzB08RyL5z8AGwVBux/3acIOOoqoj+zOvxK9QjOI="),
        };
    }
}
